### ISSUE TITLE
Couple of URL-related gotchas

### ISSUE THREAD

**Issue by obrl-soil** [DavisVaughan/extrachecks#20] opened 2022-04-17 02:00 UTC
Per https://github.com/obrl-soil/h3jsr/commit/a0f0bc2d1b0f22539414c253ee4b5debf9b8bc4b, URL fragments aren't allowed

Per https://github.com/obrl-soil/mpspline2/commit/5530ad3cb70ae4385324a80bfc7d2d02c669a56e, DOI URLs have to be in `\doi{}` not `\href{}` - which may require some in-text rearrangement as you can't use alt-text with `\doi{}`.

**Comment by DavisVaughan** [comment] 2022-04-18 14:32
Is there any way you can please post CRAN's exact email response about the URL fragment issue? That is new to me and I feel like we've done this before without any issues

For the other one, since rhub picks it up (meaning you can probably trigger this locally), I think that is out of scope for extrachecks.

**Comment by obrl-soil** [comment] 2022-04-18 22:27
Found the first one, its actually a bit more ambiguous than I remembered --

   Found the following (possibly) invalid URLs:
     URL: 
https://h3geo.org/docs/core-library/coordsystems#faceijk-coordinates 
(moved to https://h3geo.org/docs/core-library/coordsystems/)
       From: inst/doc/intro-to-h3jsr.html
       Status: 200
       Message: OK
Please change http --> https, add trailing slashes, or follow moved 
content as appropriate.

It was already https, a trailing slash on a fragment breaks the link, and the content hadn't moved, so I just went with dropping the fragment rather than arguing about it.

As for the other, yes rhub picks it up but local use of devtools::check() doesn't. I guess that may change in future updates.

**Comment by hadley** [comment] 2022-04-19 11:46
The problem is that you were missing the trailing slash on the url. It should be `https://h3geo.org/docs/core-library/coordsystems/#faceijk-coordinates`

**Comment by DavisVaughan** [comment] 2022-04-19 13:13
Just to be really explicit here:

This (with no `/`)

```
https://h3geo.org/docs/core-library/coordsystems#faceijk-coordinates
```

redirects to:

```
https://h3geo.org/docs/core-library/coordsystems/#faceijk-coordinates
```

It does that if you just paste the url in a browser and hit enter.

That is what CRAN doesn't like. They don't want redirects in your URLs. You can check for these kinds of issues in your package with the urlchecker package. i.e. if I put that bad URL in a package README then I get this:

```r
> urlchecker::url_check()
! Warning: README.md:166:2 Moved
<https://h3geo.org/docs/core-library/coordsystems#faceijk-coordinates>
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 https://h3geo.org/docs/core-library/coordsystems/
```

If I include the `/` correctly, then I don't get the redirect.

Surprisingly I don't have a bullet point about redirecting URLs, so I'll add one for that

**Closed as completed** 2022-04-19 13:25 UTC

**Comment by obrl-soil** [comment] 2022-04-20 00:45
Ah flip, I was putting the trailing slash right on the end, not before the hash 🤦‍♀️thanks fellas
